version: '3.1'

services:
  db:
    image: postgres:15
    restart: always
    ports:
      - ${DB_PORT}
    environment:
      POSTGRES_DB: ${DB_NAME}
      #POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}

    container_name: vue_db

    volumes:

      - "./postgres_data:/var/lib/postgresql/data"
